config/routes.rb
Rails.application.routes.draw do
  resources :ips
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ip.rb
class Ip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ips_controller.rb
class IpsController < ApplicationController
  before_action :set_ip, only: [:show, :edit, :update, :destroy]

  # GET /ips
  # GET /ips.json
  def index
    @ips = Ip.all
  end

  # GET /ips/1
  # GET /ips/1.json
  def show
  end

  # GET /ips/new
  def new
    @ip = Ip.new
  end

  # GET /ips/1/edit
  def edit
  end

  # POST /ips
  # POST /ips.json
  def create
    @ip = Ip.new(ip_params)

    respond_to do |format|
      if @ip.save
        format.html { redirect_to @ip, notice: 'Ip was successfully created.' }
        format.json { render :show, status: :created, location: @ip }
      else
        format.html { render :new }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ips/1
  # PATCH/PUT /ips/1.json
  def update
    respond_to do |format|
      if @ip.update(ip_params)
        format.html { redirect_to @ip, notice: 'Ip was successfully updated.' }
        format.json { render :show, status: :ok, location: @ip }
      else
        format.html { render :edit }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ips/1
  # DELETE /ips/1.json
  def destroy
    @ip.destroy
    respond_to do |format|
      format.html { redirect_to ips_url, notice: 'Ip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ip
      @ip = Ip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ip_params
      params.fetch(:ip, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ips_helper.rb
module IpsHelper
end

app/views/ips/_form.html.erb
<%= form_with(model: ip, local: true) do |form| %>
  <% if ip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ip.errors.count, "error") %> prohibited this ip from being saved:</h2>

      <ul>
        <% ip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ips/edit.html.erb
<h1>Editing Ip</h1>

<%= render 'form', ip: @ip %>

<%= link_to 'Show', @ip %> |
<%= link_to 'Back', ips_path %>

app/views/ips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ips</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ips.each do |ip| %>
      <tr>
        <td><%= link_to 'Show', ip %></td>
        <td><%= link_to 'Edit', edit_ip_path(ip) %></td>
        <td><%= link_to 'Destroy', ip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ip', new_ip_path %>

app/views/ips/new.html.erb
<h1>New Ip</h1>

<%= render 'form', ip: @ip %>

<%= link_to 'Back', ips_path %>

app/views/ips/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ip_path(@ip) %> |
<%= link_to 'Back', ips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>